# -*- coding: utf-8 -*-
"""Hoteles modelo ML .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vw_CSL9QhGNOQb9qerUro0FeitYJW2Ec
"""

import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler
from IPython.display import display

# DataFrame de Destinos
destinos_colombia = pd.DataFrame({
    'Destino': ['Cartagena', 'San Andres', 'Medellin', 'Bogotá', 'Ibagué',
                'Santa Marta', 'Cali', 'Bucaramanga', 'Villa de Leyva', 'Leticia',
                'Manizales', 'Pereira', 'Armenia', 'Popayán', 'Pasto',
                'Barranquilla', 'Cúcuta', 'Neiva', 'Salento', 'Guatapé'],
    'Playa':[1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0],
    'Cultura':[1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1],
    'Naturaleza':[1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1],
    'VidaNocturna':[1,1,1,1,0,1,1,1,0,0,1,1,0,0,0,1,1,1,0,0],
    'Gastronomia':[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
})
destinos_colombia.set_index('Destino', inplace=True)

# DataFrame de Hoteles
datos_hoteles = [
    # Cartagena
    ['Cartagena', 'Hotel Caribe by Faranda Grand', 'Lujo', '$$$$', 4.5, 'Histórico, frente al mar, piscina icónica'],
    ['Cartagena', 'Sofitel Legend Santa Clara', 'Lujo', '$$$$', 4.8, 'Lujo icónico en antiguo convento, spa'],
    ['Cartagena', 'Hotel Boutique Nacar by Tcherassi', 'Boutique', '$$$', 4.6, 'Diseño sofisticado, terraza con piscina'],
    ['Cartagena', 'Hostal Getsemaní Life', 'Hostal', '$$', 4.0, 'Céntrico en Getsemaní, económico, buen ambiente'],

    # San Andres
    ['San Andres', 'Hotel Decameron Isleño', 'Cadena', '$$$', 4.3, 'Todo incluido, playa principal, piscina'],
    ['San Andres', 'GHL Hotel Sunrise', 'Cadena', '$$$', 4.0, 'Vista al mar, piscina natural, familiar'],
    ['San Andres', 'Viajero San Andres Hostel', 'Hostal', '$$', 4.2, 'Ambiente joven, céntrico, actividades'],

    # Medellin
    ['Medellin', 'The Click Clack Hotel Medellín', 'Boutique', '$$$', 4.7, 'Diseño innovador, El Poblado, restaurante top'],
    ['Medellin', 'El Poblado Alejandría', 'Cadena', '$$$', 4.4, 'Buena ubicación en El Poblado, negocios y placer'],
    ['Medellin', 'Los Patios Hostal Boutique', 'Hostal', '$$', 4.6, 'Terraza con vistas, actividades sociales, moderno'],
    ['Medellin', 'Hotel Nutibara', 'Tradicional', '$$', 3.8, 'Ubicación céntrica histórica, tradicional'],

    # Bogotá
    ['Bogotá', 'The Click Clack Hotel Bogotá', 'Boutique', '$$$', 4.6, 'Diseño único, Parque de la 93, experiencias'],
    ['Bogotá', 'W Bogotá', 'Lujo', '$$$$', 4.7, 'Lujo moderno, spa de primera, Usaquén'],
    ['Bogotá', 'La Candelaria Hotel Boutique', 'Boutique', '$$$', 4.5, 'Encanto colonial en La Candelaria, acogedor'],
    ['Bogotá', 'Selina La Candelaria Bogota', 'Hostal', '$$', 4.3, 'Social, coworking, corazón de La Candelaria'],

    # Ibagué
    ['Ibagué', 'Hotel Estelar Altamira', 'Cadena', '$$$', 4.4, 'Piscina amplia, centro de convenciones, familiar'],
    ['Ibagué', 'Hotel Dann Combeima', 'Cadena', '$$', 4.2, 'Ubicación céntrica, tradicional, negocios'],
    ['Ibagué', 'Ayenda La Casona de los Periodistas', 'Económico', '$', 3.9, 'Económico, limpio, funcional'],

    # Santa Marta
    ['Santa Marta', 'Santa Marta Marriott Resort Playa Dormida', 'Lujo', '$$$$', 4.5, 'Acceso directo a playa, piscinas, moderno'],
    ['Santa Marta', 'Hotel Boutique Don Pepe', 'Boutique', '$$$', 4.7, 'Casa colonial restaurada, spa, céntrico'],
    ['Santa Marta', 'Masaya Hostel Santa Marta', 'Hostal', '$$', 4.4, 'Piscina en azotea, bar, ambiente social'],

    # Cali
    ['Cali', 'InterContinental Cali', 'Lujo', '$$$$', 4.6, 'Piscina grande, vistas al río Cali, tradición'],
    ['Cali', 'Hotel Spiwak Chipichape Cali', 'Boutique', '$$$', 4.5, 'Diseño moderno, junto a centro comercial Chipichape'],
    ['Cali', 'El Viajero Salsa School & Hostel', 'Hostal', '$', 4.3, 'Clases de salsa, ambiente festivo, patio'],

    # Bucaramanga
    ['Bucaramanga', 'Hotel Dann Carlton Bucaramanga', 'Cadena', '$$$', 4.5, 'Lujo clásico, piscina, spa, buenas vistas'],
    ['Bucaramanga', 'Hotel Buena Vista Express', 'Boutique', '$$', 4.3, 'Vistas panorámicas, moderno, confortable'],
    ['Bucaramanga', 'Kasa Guane Bucaramanga', 'Hostal', '$', 4.1, 'Terraza agradable, económico, céntrico'],

    # Villa de Leyva
    ['Villa de Leyva', 'Hotel Posada de San Antonio', 'Tradicional', '$$', 4.4, 'Casa colonial, patios internos, tranquilo'],
    ['Villa de Leyva', 'Hotel Duruelo', 'Tradicional', '$$$', 4.5, 'Amplias zonas verdes, piscina climatizada, spa'],

    # Leticia
    ['Leticia', 'Decameron Decalodge Ticuna', 'Cadena', '$$$', 4.0, 'Experiencia amazónica, piscina, todo incluido opcional'],
    ['Leticia', 'Waira Suites', 'Boutique', '$$', 4.2, 'Céntrico, piscina, cómodas habitaciones'],

    # Manizales
    ['Manizales', 'Hotel Termales El Otoño', 'Resort', '$$$', 4.6, 'Aguas termales naturales, vistas a la montaña, spa'],
    ['Manizales', 'Estelar Recinto del Pensamiento Hotel', 'Cadena', '$$', 4.4, 'Entorno natural, mariposario, eventos'],
    ['Manizales', 'Hostal de la Montaña', 'Hostal', '$', 4.0, 'Acogedor, cerca al Cable Aéreo, económico'],

    # Pereira
    ['Pereira', 'Movich Hotel de Pereira', 'Lujo', '$$$$', 4.7, 'Vistas panorámicas de la ciudad, spa, diseño'],
    ['Pereira', 'Sonesta Hotel Pereira', 'Cadena', '$$$', 4.5, 'Moderno, centro de convenciones, piscina'],
    ['Pereira', 'Kolibri Hostel', 'Hostal', '$', 4.2, 'Jardín amplio, ambiente relajado, tours de café'],

    # Armenia
    ['Armenia', 'Armenia Hotel Estelar', 'Cadena', '$$$', 4.3, 'Piscina, ideal para familias, cerca a parques temáticos'],
    ['Armenia', 'Hotel Mocawa Plaza Armenia', 'Boutique', '$$', 4.4, 'Diseño moderno, céntrico, terraza con vistas'],
    ['Armenia', 'Hostel Coffee Town', 'Hostal', '$', 4.0, 'Temática cafetera, económico, tours'],

    # Popayán
    ['Popayán', 'Hotel Dann Monasterio Popayán', 'Histórico/Lujo', '$$$$', 4.7, 'Antiguo monasterio, spa, alta cocina, historia'],
    ['Popayán', 'Hotel La Plazuela Popayán', 'Boutique', '$$', 4.3, 'Ubicación céntrica, encanto colonial, patio'],
    ['Popayán', 'Hostal Caracolí', 'Hostal', '$', 4.0, 'Casa colonial, ambiente tranquilo, económico'],

    # Pasto
    ['Pasto', 'Hotel V1501', 'Boutique', '$$$', 4.5, 'Diseño moderno y elegante, céntrico, confort'],
    ['Pasto', 'Loft Hotel Pasto', 'Cadena', '$$', 4.2, 'Funcional, buena ubicación para negocios y turismo'],
    ['Pasto', 'Chalet Guamuez Hostal', 'Hostal/Ecolodge', '$', 4.1, 'Cerca a la Laguna de la Cocha, entorno natural'],

    # Barranquilla
    ['Barranquilla', 'Hotel El Prado', 'Histórico/Lujo', '$$$$', 4.5, 'Edificio patrimonio, piscina grande, tradición y lujo'],
    ['Barranquilla', 'Movich Buró 51', 'Cadena', '$$$', 4.6, 'Moderno, ideal para negocios, piscina en la azotea'],
    ['Barranquilla', 'The Meeting Point Hostel', 'Hostal', '$', 4.2, 'Ambiente social, céntrico, ideal para mochileros'],

    # Cúcuta
    ['Cúcuta', 'Hampton by Hilton Cúcuta', 'Cadena', '$$$', 4.4, 'Moderno, desayuno incluido, estándar internacional'],
    ['Cúcuta', 'Hotel Casino Internacional', 'Cadena', '$$', 4.2, 'Casino, entretenimiento, piscina, céntrico'],
    ['Cúcuta', 'Hotel Zaraya', 'Económico', '$', 3.9, 'Funcional, económico, cerca a la frontera'],

    # Neiva
    ['Neiva', 'GHL Hotel Neiva', 'Cadena', '$$$', 4.1, 'Piscina, moderno, buen servicio, negocios'],
    ['Neiva', 'Hotel Neiva Plaza', 'Tradicional', '$$', 3.9, 'Céntrico, tradicional, económico'],

    # Salento
    ['Salento', 'Hotel Salento Real Eje Cafetero', 'Tradicional', '$$', 4.3, 'Cerca a la plaza principal, arquitectura típica'],
    ['Salento', 'BetaHotel Salento', 'Boutique', '$$$', 4.6, 'Diseño moderno con toques rústicos, vistas'],
    ['Salento', 'Coffee Tree Boutique Hostel', 'Boutique', '$$$', 4.7, 'Jardín exuberante, ambiente cafetero, confort'],

    # Guatapé
    ['Guatapé', 'Hotel Santorini Kasamador', 'Boutique', '$$$', 4.5, 'Vistas a la represa, estilo mediterráneo, tranquilo'],
    ['Guatapé', 'Hotel Zócalos Campestre', 'Campestre', '$$', 4.2, 'Entorno natural, cerca al pueblo, zócalos'],
]

columnas_hoteles = ['Destino', 'Nombre_Hotel', 'Tipo_Hotel', 'Rango_Precio', 'Puntuacion', 'Caracteristica_Clave']
hoteles_info_df = pd.DataFrame(datos_hoteles, columns=columnas_hoteles)


print("DataFrame de Hoteles (primeras filas):")
display(hoteles_info_df.head())
print("\nDataFrame de Destinos (primeras filas):")
display(destinos_colombia.head())

column_features_order = ['Playa', 'Cultura', 'Naturaleza', 'VidaNocturna', 'Gastronomia']

def pedir_preferencias(caracteristica):
    while True:
        try:
            valor = int(input(f"Te gusta '{caracteristica}' (1:Si ó 0:No): "))
            if valor in {0, 1}:
                return valor
            else:
                print(f"Por favor ingrese un valor valido (0 ó 1) para '{caracteristica}'.")
        except ValueError:
            print(f"Por favor ingrese un valor numérico de 0 ó 1 para '{caracteristica}'.")



preferencias_usuario_dict = {}
for feature in column_features_order:
    preferencias_usuario_dict[feature] = pedir_preferencias(feature)

usuario = pd.DataFrame([preferencias_usuario_dict], columns=column_features_order)
print("\n--- Tus Preferencias ---")
display(usuario)

scaler_destinos = StandardScaler()
destinos_colombia_features_to_scale = destinos_colombia[column_features_order]
destinos_colombia_scaled = scaler_destinos.fit_transform(destinos_colombia_features_to_scale)
usuario_scaled = scaler_destinos.transform(usuario)

similitud_destinos = cosine_similarity(destinos_colombia_scaled, usuario_scaled)
recomendaciones_destinos_df = pd.DataFrame(similitud_destinos, columns=['Similitud_Destino'], index=destinos_colombia.index)

print("\n--- Similitud de Hoteles---")
hotel_puntuaciones = hoteles_info_df[['Puntuacion']].values
scaler_hoteles_puntuacion = StandardScaler()
hotel_puntuaciones_scaled = scaler_hoteles_puntuacion.fit_transform(hotel_puntuaciones)
hotel_features_artificial = np.tile(hotel_puntuaciones_scaled, (1, len(column_features_order)))
similitud_hoteles_calculada = cosine_similarity(hotel_features_artificial, usuario_scaled)

# Crear el DataFrame de recomendaciones de hoteles con todas las columnas necesarias
recomendaciones_hoteles_df = pd.DataFrame({
    'Nombre_Hotel': hoteles_info_df['Nombre_Hotel'],
    'Similitud_Hotel': similitud_hoteles_calculada.flatten(),
    'Destino_Hotel': hoteles_info_df['Destino'],
    'Puntuacion_Hotel': hoteles_info_df['Puntuacion'],
    'Tipo_Hotel': hoteles_info_df['Tipo_Hotel'],
    'Rango_Precio': hoteles_info_df['Rango_Precio'],
    'Caracteristica_Clave': hoteles_info_df['Caracteristica_Clave']
}).set_index('Nombre_Hotel')


# --- Mostrar Resultados ---
top_n_destinos_display = 3 # Mostramos el top 3 de destinos

print(f"\n--- Top {top_n_destinos_display} Destinos Recomendados ---")
top_destinos_recomendados = recomendaciones_destinos_df.sort_values(by='Similitud_Destino', ascending=False).head(top_n_destinos_display)
display(top_destinos_recomendados)

# Logica para mostrar Hoteles recomendados
print(f"\n--- Hoteles Sugeridos en los Top {top_n_destinos_display} Destinos Recomendados ---")
lista_nombres_destinos_top = top_destinos_recomendados.index.tolist()

if not lista_nombres_destinos_top:
    print("No se encontraron destinos principales para recomendar hoteles.")
else:
    for nombre_destino in lista_nombres_destinos_top:
        print(f"\n🏨 Hoteles en: {nombre_destino} (Similitud Destino: {top_destinos_recomendados.loc[nombre_destino, 'Similitud_Destino']:.2f}")

        # Filtrar hoteles para el destino actual0
        hoteles_en_destino_actual = recomendaciones_hoteles_df[recomendaciones_hoteles_df['Destino_Hotel'] == nombre_destino]

        if hoteles_en_destino_actual.empty:
            print(f"  No se encontraron hoteles en nuestra base de datos para {nombre_destino}.")
        else:
            hoteles_ordenados = hoteles_en_destino_actual.sort_values(by='Similitud_Hotel', ascending=False)
            display(hoteles_ordenados[['Destino_Hotel', 'Puntuacion_Hotel', 'Tipo_Hotel', 'Rango_Precio', 'Caracteristica_Clave',]].head(2))

